# Generated by Django 5.1.6 on 2025-04-05 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0002_alter_user_profile_picture_event_contents_messages_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contents',
            new_name='Content',
        ),
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
