# Generated by Django 5.1.6 on 2025-04-05 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0003_rename_contents_content_rename_messages_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=30, unique=True)),
                ('id_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreApp.event')),
            ],
        ),
    ]
