# Generated by Django 5.1.6 on 2025-04-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0004_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('id_event', 'tag_name')},
        ),
    ]
