# Generated by Django 5.1.6 on 2025-04-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0005_alter_tag_tag_name_alter_tag_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/events/'),
        ),
    ]
