# Generated by Django 5.1.6 on 2025-04-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0007_alter_user_first_name_alter_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='coreApp.tag'),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='id_event',
        ),
    ]
