# Generated by Django 5.1.6 on 2025-04-05 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_posted', models.DateTimeField(blank=True, null=True)),
                ('is_listed', models.BooleanField(default=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('event_picture', models.ImageField(blank=True, null=True, upload_to='images/users/')),
                ('id_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_saved', models.FileField(upload_to='documents/')),
                ('audio_extracted', models.FileField(null=True, upload_to='audios/')),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.event')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_sender', models.CharField(max_length=30)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.event')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_date', models.DateTimeField(auto_now=True)),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('left_date', models.DateTimeField(null=True)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.event')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.user')),
            ],
            options={
                'unique_together': {('id_event', 'id_user')},
            },
        ),
    ]
